version: '3.8'

networks:
  public-network:
    driver: bridge

services:
  api:
    container_name: codechat_api
    image: codechat/api:develop
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - instances_connecteds:/codechat/instances
    environment:
      - SERVER_PORT=3000
      - SESSION_SECRET=${SESSION_SECRET}

      - LOG_LEVEL=ERROR|WARN|INFO|DEBUG|LOG|VERBOSE|DARK
      - LOG_COLOR=true

      - DATABASE_ENABLED=true
      - DATABASE_URL=${DB_CONNECTION_STRING}
      - DATABASE_SYNC_MESSAGES=true
      - DATABASE_SAVE_DATA_NEW_MESSAGE=true
      - DATABASE_SAVE_MESSAGE_UPDATE=true
      - DATABASE_SAVE_DATA_CONTACTS=true
      - DATABASE_SAVE_DATA_CHATS=true

      - GLOBAL_WEBHOOK_URL=${GLOBAL_WEBHOOK_URL}
      - GLOBAL_WEBHOOK_ENABLED=${GLOBAL_WEBHOOK_ENABLED}

      - INSTANCE_EXPIRATION_TIME=false

      - CONFIG_SESSION_PHONE_CLIENT=nexplot
      - CONFIG_SESSION_PHONE_NAME=Edge

      - WA_VERSION=[ 2, 3000, 1015901307 ]

      - QRCODE_LIMIT=10
      - QRCODE_EXPIRATION_TIME=60

      - CONNECTION_TIMEOUT=300

      - AUTHENTICATION_GLOBAL_AUTH_TOKEN=${AUTHENTICATION_GLOBAL_AUTH_TOKEN}
      - AUTHENTICATION_JWT_EXPIRES_IN=${AUTHENTICATION_JWT_EXPIRES_IN}
      - AUTHENTICATION_JWT_SECRET=${AUTHENTICATION_JWT_SECRET}

      - PROVIDER_ENABLED=false
      - PROVIDER_HOST=127.0.0.1
      - PROVIDER_PORT=5656
      - PROVIDER_PREFIX=codechat

      - API_BACKEND=${API_BACKEND}

      # - S3_ENABLED=false
      # - S3_ACCESS_KEY=[ACCESS_KEY]
      # - S3_SECRET_KEY=[SECRET_KEY]
      # - S3_BUCKET=[BUCKET]
      # - S3_PORT=9000
      # - S3_ENDPOINT=[ENDPOINT]
      # - S3_USE_SSL=false
    networks:
      - public-network

volumes:
  instances_connecteds:
    driver: local
